language: cpp
dist: xenial
osx_image: xcode10.1

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  matrix:
  - TARGET=debug
  - TARGET=release

matrix:
  exclude:
    - os: linux
      compiler: clang

    - os: osx
      compiler: gcc

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update -qq;
      sudo apt-get install -qqq scons pkg-config build-essential zip;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install scons;
    fi

script:
  - scons target="$TARGET" bits=64 generate_bindings=yes
  - pushd bin
  - for file in *; do
      zip -mr9 "$file.zip" "$file";
    done
  - popd

deploy:
  provider: releases
  api_key:
    secure: wty6uRB+kzhYdlLV+pt6pzQSjLMr07kLl9cJjet5Jb4fgmFLyqLB4Mv7a5OdXJuUdGmKoZe3u3FKjlrD5Xh4aGZHKmw6QHHSQ4do5WYngOQ6Ybb7QJ7hTOIJqBaNX59ZAylnvK+NvMz6hlmwEjOnyIBAoc+VzcSczZU5qcgDcfd7qlBst4jyyiegneCnJVoUBcP9fdsz91xyohhceCvp+inidaBoIQLvCGkRC3KpDrPUHQMASW8Za7jg6G91DYEbv+1JovdGNEnSICHZYLrQ0GDPRxtNAadh0J4xfSaVhaYeKJA62w0X5KGB3J/Qiadc1UbpEDFU6EEreNxwUCv8ZAWFuhYukZZQmPXI5rrX0KDZ6SVDPoIxSoYTx4d4HBeT9K3bEhd0zJ+OgHAEczy4hCVNzVUNuqlIq72wE6woEoe/zezDg0GAidF5Ky72uHxmd4C4yZVt4JoVbb1I9c/ooA5PIJj+tfkgl1zbhDmhBYzqO+PuM6XXiD5cwCmuhrwkKMTdBc7+Y9OH9Kw5CfCzm1fPJyca1oZcER7Q6A65WQGJnCPFYpadoRHh9JuJ3TIE3f+SFwuPu8LuJL5QPPOWzQttpk9L7t06nymwpoUdloufo7nWDHjPhsmvGcuM6uoH+KLyyEgmafhxHDT7HMTJgxN4qfhQQEr9aHvsrTnC0Fo=
  skip_cleanup: true
  file_glob: true
  file: bin/*
  on:
    repo: Calinou/godot-cpp
